server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.100.4:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    zookeeper:
      connect-string: 192.168.100.4:2181