server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: localhost:1111 #nacos cluster; 1111 port is nginx port

management:
  endpoints:
    web:
      exposure:
        include: '*'