server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1111
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719 # 默认8719端口，如果被占用会自动从8719开始依次+1扫描，直到找到未被占用的端口
        datasource:
          ds1:
            nacos:
              server-addr: localhost:3333
              dataId: cloudalibaba-sentinel-service
              data-type: json
              rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'